Use flock to lock the lock file
pmem/vltrace pull request #15
Opened 2017-07-21 14:15 UTC by ldorau

2017-07-27 10:32 UTC, marcinslusarz requested changes

2017-07-27 10:32 UTC, marcinslusarz commented on src/vltrace.c
> +	(void) asprintf(&buf, "%i \n", getpid());
I suspect I know why you put space before \n, but this is ugly approach - just truncate the file before writing anything.

2017-07-27 11:55 UTC, ldorau commented on src/vltrace.c
> +	(void) asprintf(&buf, "%i \n", getpid());
Done

2017-07-27 12:09 UTC, marcinslusarz commented
*[src/vltrace.c, line 74 at r2](https://reviewable.io:443/reviews/pmem/vltrace/15#-Kq2wZDpxboru4c1pfAQ:-Kq2wZDpxboru4c1pfAR:btjogec) ([raw file](https://github.com/pmem/vltrace/blob/91f20cc8de65c3fb39f1b239f8618bccec7bca64/src/vltrace.c#L74)):*
> ```C
> #define VLTRACE_NAME		"vltrace"
> #define LEN_VLTRACE_NAME	7
> #define FILE_LOCK		"/tmp/"VLTRACE_NAME"-lock-file.pid"
> ```

This seem like an unrelated change (separate commit or at least mention it in commit message please) and I'm not sure it's correct.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/vltrace/15)*
<!-- Sent from Reviewable.io -->

2017-07-27 14:13 UTC, ldorau commented
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/vltrace.c, line 74 at r2](https://reviewable.io:443/reviews/pmem/vltrace/15#-Kq2wZDpxboru4c1pfAQ:-Kq3OLX4oVlsYJvmavP3:b-910xan) ([raw file](https://github.com/pmem/vltrace/blob/91f20cc8de65c3fb39f1b239f8618bccec7bca64/src/vltrace.c#L74)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

This seem like an unrelated change (separate commit or at least mention it in commit message please) and I'm not sure it's correct.
</blockquote></details>

Path set to /var/lock

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/vltrace/15)*
<!-- Sent from Reviewable.io -->

2017-07-28 08:40 UTC, marcinslusarz commented
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/vltrace/15#-:-Kq7LZJjafnDcwkyBm_o:bnfp4nl)*
<!-- Sent from Reviewable.io -->

2017-07-28 08:40 UTC, marcinslusarz approved these changes

2017-07-28 08:41 UTC, merged